categories:
  MainzificRim13:
    label: 'mainzific-rim-13'
  MainzificRim13.templates:
    label: 'Templates'
    parent: MainzificRim13
  MainzificRim13.layout:
    label: 'Layout'
    parent: MainzificRim13
  MainzificRim13.menus:
    label: 'Menus'
    parent: MainzificRim13

settings:
  MainzificRim13.template_path:
    label: 'Page template path'
    category: MainzificRim13.templates
    description: 'Path to the templates of the mainzific-rim-13.'
    type: string
    default: 'EXT:mainzific_rim13/Resources/Private/Templates/'

  MainzificRim13.logo:
    label: 'Logo'
    category: MainzificRim13.layout
    description: 'Path to the logo of mainzific-rim-13.'
    type: string
    default: 'EXT:mainzific_rim13/Resources/Public/Images/logo.svg'

  MainzificRim13.logo-alt:
    label: 'Logo Alt text'
    category: MainzificRim13.layout
    description: 'Alternative text of the logo for the visually impaired'
    type: string
    default: 'Logo'

  MainzificRim13.favicon:
    label: 'Favicon'
    description: 'This icon is displayed in search engine results and in the browser tab'
    category: MainzificRim13.layout
    type: string
    default: 'EXT:mainzific_rim13/Resources/Public/Icons/favicon.ico'

  MainzificRim13.footerMenuRoot:
      label: 'Footer menu root uid'
      description: 'The subpages of this page are displayed in the footer'
      category: MainzificRim13.menus
      type: int
      default: 2
